# see http://about.travis-ci.org/docs/user/languages/php/
language: php

# List of PHP versions to test against
php:
  # Using major version aliases

  # Alias for the most recent 5.4
  - 5.4
  # Alias for the most recent 5.5
  - 5.5

before_script:
  - composer selfupdate
  - composer update

script:
  - phpunit --configuration ./phpunit.xml.dist